export function createCodexWebComposition(deps) {
  let renderThreads = () => {};
  let upsertProvisionalThreadItem = () => false;
  let wireThreadPullToRefresh = () => {};
  let startThreadAutoRefreshLoop = () => {};
  let startActiveThreadLivePollLoop = () => {};
  const localStorageRef =
    deps.localStorageRef ??
    (typeof localStorage === "undefined" ? undefined : localStorage);
  const documentRef =
    deps.documentRef ??
    (typeof document === "undefined" ? undefined : document);
  const windowRef =
    deps.windowRef ??
    (typeof window === "undefined" ? undefined : window);
  const requestAnimationFrameRef =
    deps.requestAnimationFrameRef ??
    (typeof requestAnimationFrame === "undefined"
      ? ((cb) => setTimeout(cb, 0))
      : requestAnimationFrame);
  const MutationObserverRef =
    deps.MutationObserverRef ??
    (typeof MutationObserver === "undefined" ? class {} : MutationObserver);

  const { api, connectWs, handleWsPayload, syncEventSubscription, wsCall, wsSend } = deps.createWsClientModule({
    state: deps.state,
    setStatus: deps.setStatus,
    addChat: (...args) => chatTimeline.addChat(...args),
    clearTransientToolMessages: deps.clearTransientToolMessages,
    setRuntimeActivity: deps.setRuntimeActivity,
    toRecord: deps.toRecord,
    readString: deps.readString,
    readNumber: deps.readNumber,
    resetEventReplayState: deps.resetEventReplayState,
    markEventIdSeen: deps.markEventIdSeen,
    extractNotificationEventId: deps.extractNotificationEventId,
    extractNotificationThreadId: deps.extractNotificationThreadId,
    shouldRefreshThreadsFromNotification: deps.shouldRefreshThreadsFromNotification,
    shouldRefreshActiveThreadFromNotification: deps.shouldRefreshActiveThreadFromNotification,
    scheduleThreadRefresh: deps.scheduleThreadRefresh,
    scheduleActiveThreadRefresh: deps.scheduleActiveThreadRefresh,
    renderLiveNotification: (...args) => deps.renderLiveNotification(...args),
    applyPendingPayloads: (...args) => applyPendingPayloads(...args),
    addChat: (...args) => addChat(...args),
    upsertProvisionalThreadItem: (...args) => upsertProvisionalThreadItem(...args),
    recordWebTransportEvent: deps.recordWebTransportEvent,
    LAST_EVENT_ID_KEY: deps.LAST_EVENT_ID_KEY,
    transportMode: deps.transportMode,
  });

  const workspaceUi = deps.createWorkspaceUiModule({
    state: deps.state,
    byId: deps.byId,
    api,
    normalizeWorkspaceTarget: deps.normalizeWorkspaceTargetInModule,
    WORKSPACE_TARGET_KEY: deps.WORKSPACE_TARGET_KEY,
    START_CWD_BY_WORKSPACE_KEY: deps.START_CWD_BY_WORKSPACE_KEY,
    detectThreadWorkspaceTarget: deps.detectThreadWorkspaceTarget,
    updateHeaderUi: deps.updateHeaderUi,
    renderFolderPicker: (...args) => renderFolderPicker(...args),
    setStatus: deps.setStatus,
    pushThreadAnimDebug: deps.pushThreadAnimDebug,
    isThreadListActuallyVisible: (...args) => isThreadListActuallyVisible(...args),
      buildThreadRenderSig: deps.buildThreadRenderSig,
      applyThreadFilter: (...args) => applyThreadFilter(...args),
      refreshThreads: (...args) => refreshThreads(...args),
      syncEventSubscription,
      renderThreads: (...args) => renderThreads(...args),
    });

  const chatViewport = deps.createChatViewportModule({
    state: deps.state,
    byId: deps.byId,
    dbgSet: deps.dbgSet,
    CHAT_LIVE_FOLLOW_MAX_STEP_PX: deps.CHAT_LIVE_FOLLOW_MAX_STEP_PX,
    CHAT_LIVE_FOLLOW_BTN_THROTTLE_MS: deps.CHAT_LIVE_FOLLOW_BTN_THROTTLE_MS,
  });

  const imageViewer = deps.createImageViewerModule({
    byId: deps.byId,
    state: deps.state,
    escapeHtml: deps.escapeHtml,
    wireBlurBackdropShield: deps.wireBlurBackdropShield,
    scrollChatToBottom: chatViewport.scrollChatToBottom,
    updateScrollToBottomBtn: chatViewport.updateScrollToBottomBtn,
  });

  const chatTimeline = deps.createChatTimelineModule({
    byId: deps.byId,
    state: deps.state,
    escapeHtml: deps.escapeHtml,
    renderMessageAttachments: deps.renderMessageAttachments,
    renderMessageBody: deps.renderMessageBody,
    wireMessageLinks: deps.wireMessageLinks,
    wireMessageAttachments: imageViewer.wireMessageAttachments,
    scheduleChatLiveFollow: chatViewport.scheduleChatLiveFollow,
    updateScrollToBottomBtn: chatViewport.updateScrollToBottomBtn,
    scrollChatToBottom: chatViewport.scrollChatToBottom,
    renderRuntimePanels: deps.renderRuntimePanels,
  });

  const historyLoader = deps.createHistoryLoaderModule({
    state: deps.state,
    byId: deps.byId,
    api,
    nextFrame: deps.nextFrame,
    waitMs: deps.waitMs,
    HISTORY_WINDOW_THRESHOLD: deps.HISTORY_WINDOW_THRESHOLD,
    normalizeThreadTokenUsage: deps.normalizeThreadTokenUsage,
    renderComposerContextLeft: deps.renderComposerContextLeft,
    detectThreadWorkspaceTarget: deps.detectThreadWorkspaceTarget,
    parseUserMessageParts: deps.parseUserMessageParts,
    isBootstrapAgentsPrompt: deps.isBootstrapAgentsPrompt,
    normalizeThreadItemText: deps.normalizeThreadItemText,
    normalizeType: deps.normalizeType,
    stripCodexImageBlocks: deps.stripCodexImageBlocks,
    hideWelcomeCard: deps.hideWelcomeCard,
    showWelcomeCard: deps.showWelcomeCard,
    updateHeaderUi: deps.updateHeaderUi,
    updateScrollToBottomBtn: chatViewport.updateScrollToBottomBtn,
    scheduleChatLiveFollow: chatViewport.scheduleChatLiveFollow,
    scrollChatToBottom: chatViewport.scrollChatToBottom,
    scrollToBottomReliable: chatViewport.scrollToBottomReliable,
    canStartChatLiveFollow: chatViewport.canStartChatLiveFollow,
    renderMessageBody: deps.renderMessageBody,
    addChat: chatTimeline.addChat,
    buildMsgNode: chatTimeline.buildMsgNode,
    clearChatMessages: chatTimeline.clearChatMessages,
    showTransientToolMessage: deps.showTransientToolMessage,
    showTransientThinkingMessage: deps.showTransientThinkingMessage,
    clearTransientToolMessages: deps.clearTransientToolMessages,
    clearTransientThinkingMessages: deps.clearTransientThinkingMessages,
    clearRuntimeState: deps.clearRuntimeState,
    renderRuntimePanels: deps.renderRuntimePanels,
    renderCommentaryArchive: chatTimeline.renderCommentaryArchive,
    syncRuntimeStateFromHistory: deps.syncRuntimeStateFromHistory,
    syncEventSubscription,
  });

  const modelPicker = deps.createModelPickerModule({
    state: deps.state,
    byId: deps.byId,
    api,
    waitMs: deps.waitMs,
    ensureArrayItems: deps.ensureArrayItems,
    escapeHtml: deps.escapeHtml,
    escapeAttr: deps.escapeAttr,
    compactModelLabel: deps.compactModelLabel,
    updateHeaderUi: deps.updateHeaderUi,
    persistModelsCache: deps.persistModelsCache,
    pickLatestModelId: deps.pickLatestModelId,
    SELECTED_MODEL_KEY: deps.SELECTED_MODEL_KEY,
    REASONING_EFFORT_KEY: deps.REASONING_EFFORT_KEY,
    MODEL_USER_SELECTED_KEY: deps.MODEL_USER_SELECTED_KEY,
    EFFORT_USER_SELECTED_KEY: deps.EFFORT_USER_SELECTED_KEY,
    MODEL_LOADING_MIN_MS: deps.MODEL_LOADING_MIN_MS,
  });

  const threadListRefresh = deps.createThreadListRefreshModule({
    state: deps.state,
    byId: deps.byId,
    api,
    ensureArrayItems: deps.ensureArrayItems,
    normalizeWorkspaceTarget: deps.normalizeWorkspaceTarget,
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    getStartCwdForWorkspace: workspaceUi.getStartCwdForWorkspace,
    sortThreadsByNewest: deps.sortThreadsByNewest,
    filterThreadsForWorkspace: deps.filterThreadsForWorkspace,
    hasDualWorkspaceTargets: workspaceUi.hasDualWorkspaceTargets,
    detectWorkspaceAvailabilityFromThreads: deps.detectWorkspaceAvailabilityFromThreads,
    buildThreadRenderSig: deps.buildThreadRenderSig,
    persistThreadsCache: deps.persistThreadsCache,
    syncActiveThreadMetaFromList: workspaceUi.syncActiveThreadMetaFromList,
    updateHeaderUi: deps.updateHeaderUi,
    pushThreadAnimDebug: deps.pushThreadAnimDebug,
    renderThreads: (...args) => renderThreads(...args),
    applyWorkspaceUi: workspaceUi.applyWorkspaceUi,
    setStatus: deps.setStatus,
    THREAD_FORCE_REFRESH_MIN_INTERVAL_MS: deps.THREAD_FORCE_REFRESH_MIN_INTERVAL_MS,
  });
  ({ upsertProvisionalThreadItem } = threadListRefresh);

  ({ renderThreads } = deps.createThreadListViewModule({
    state: deps.state,
    byId: deps.byId,
    escapeHtml: deps.escapeHtml,
    normalizeWorkspaceTarget: deps.normalizeWorkspaceTarget,
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    hasDualWorkspaceTargets: workspaceUi.hasDualWorkspaceTargets,
    pushThreadAnimDebug: deps.pushThreadAnimDebug,
    isThreadListActuallyVisible: threadListRefresh.isThreadListActuallyVisible,
    workspaceKeyOfThread: deps.workspaceKeyOfThread,
    truncateLabel: deps.truncateLabel,
    relativeTimeLabel: deps.relativeTimeLabel,
    pickThreadTimestamp: deps.pickThreadTimestamp,
    setMainTab: deps.setMainTab,
    setMobileTab: deps.setMobileTab,
    setActiveThread: deps.setActiveThread,
    onActiveThreadOpened: () => deps.updateMobileComposerState(),
    setChatOpening: chatTimeline.setChatOpening,
    detectThreadWorkspaceTarget: deps.detectThreadWorkspaceTarget,
    loadThreadMessages: historyLoader.loadThreadMessages,
    api,
    connectWs,
    syncEventSubscription,
    registerPendingThreadResume: deps.registerPendingThreadResume,
    onPendingTurnStateChange: () => {
      deps.updateMobileComposerState();
      deps.renderRuntimePanels();
    },
    refreshWorkspaceRuntimeState: workspaceUi.refreshWorkspaceRuntimeState,
    updateHeaderUi: deps.updateHeaderUi,
    setStatus: deps.setStatus,
    scheduleThreadRefresh: deps.scheduleThreadRefresh,
    scrollToBottomReliable: chatViewport.scrollToBottomReliable,
    FAVORITE_THREADS_KEY: deps.FAVORITE_THREADS_KEY,
  }));

  const folderPicker = deps.createFolderPickerModule({
    state: deps.state,
    byId: deps.byId,
    api,
    escapeHtml: deps.escapeHtml,
    ensureArrayItems: deps.ensureArrayItems,
    normalizeWorkspaceTarget: deps.normalizeWorkspaceTarget,
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    isWorkspaceAvailable: workspaceUi.isWorkspaceAvailable,
    setWorkspaceTarget: workspaceUi.setWorkspaceTarget,
    getStartCwdForWorkspace: workspaceUi.getStartCwdForWorkspace,
    setStartCwdForWorkspace: workspaceUi.setStartCwdForWorkspace,
    setStatus: deps.setStatus,
  });

  const connectionFlows = deps.createConnectionFlowsModule({
    state: deps.state,
    byId: deps.byId,
    api,
    wsSend,
    nextReqId: deps.nextReqId,
    connectWs,
    ensureArrayItems: deps.ensureArrayItems,
    escapeHtml: deps.escapeHtml,
    blockInSandbox: deps.blockInSandbox,
    TOKEN_STORAGE_KEY: deps.TOKEN_STORAGE_KEY,
    getEmbeddedToken: deps.getEmbeddedToken,
    refreshModels: modelPicker.refreshModels,
    refreshCodexVersions: deps.refreshCodexVersions,
    refreshWorkspaceRuntimeState: workspaceUi.refreshWorkspaceRuntimeState,
    refreshThreads: (...args) => refreshThreads(...args),
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    isWorkspaceAvailable: workspaceUi.isWorkspaceAvailable,
    setStatus: deps.setStatus,
    setMainTab: deps.setMainTab,
    setMobileTab: deps.setMobileTab,
    addChat: chatTimeline.addChat,
    renderPendingInline: (...args) => chatTimeline.renderPendingInline(...args),
  });

  const turnActions = deps.createTurnActionsModule({
    state: deps.state,
    byId: deps.byId,
    api,
    wsSend,
    wsCall,
    nextReqId: deps.nextReqId,
    connectWs,
    syncEventSubscription,
    getPromptValue: deps.getPromptValue,
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    getStartCwdForWorkspace: workspaceUi.getStartCwdForWorkspace,
    waitPendingThreadResume: deps.waitPendingThreadResume,
    registerPendingThreadResume: deps.registerPendingThreadResume,
    refreshWorkspaceRuntimeState: workspaceUi.refreshWorkspaceRuntimeState,
    updateHeaderUi: deps.updateHeaderUi,
    addChat: chatTimeline.addChat,
    clearChatMessages: chatTimeline.clearChatMessages,
    hideWelcomeCard: deps.hideWelcomeCard,
    showWelcomeCard: deps.showWelcomeCard,
    clearPromptValue: deps.clearPromptValue,
    renderComposerContextLeft: deps.renderComposerContextLeft,
    scrollToBottomReliable: chatViewport.scrollToBottomReliable,
    scheduleChatLiveFollow: chatViewport.scheduleChatLiveFollow,
    createAssistantStreamingMessage: chatTimeline.createAssistantStreamingMessage,
    appendStreamingDelta: chatTimeline.appendStreamingDelta,
    finalizeAssistantMessage: chatTimeline.finalizeAssistantMessage,
    normalizeTextPayload: deps.normalizeTextPayload,
    maybeNotifyTurnDone: deps.maybeNotifyTurnDone,
    renderAttachmentPills: deps.renderAttachmentPills,
    refreshThreads: (...args) => refreshThreads(...args),
    refreshHosts: connectionFlows.refreshHosts,
    refreshPending: connectionFlows.refreshPending,
    clearPendingUserInputs: connectionFlows.clearPendingUserInputs,
    clearSyntheticPendingUserInputById: connectionFlows.clearSyntheticPendingUserInputById,
    setSyntheticPendingUserInputs: connectionFlows.setSyntheticPendingUserInputs,
    suppressSyntheticPendingUserInputs: connectionFlows.suppressSyntheticPendingUserInputs,
    setStatus: deps.setStatus,
    setActiveThread: deps.setActiveThread,
    setMainTab: deps.setMainTab,
    setMobileTab: deps.setMobileTab,
    setChatOpening: chatTimeline.setChatOpening,
    syncPendingTurnUi: () => {
      chatTimeline.renderCommentaryArchive();
      chatTimeline.renderPendingInline();
      deps.renderRuntimePanels();
    },
    setComposerActionMenuOpen: deps.setComposerActionMenuOpen,
    updateMobileComposerState: deps.updateMobileComposerState,
    clearTransientToolMessages: deps.clearTransientToolMessages,
    clearTransientThinkingMessages: deps.clearTransientThinkingMessages,
    hideSlashCommandMenu: deps.hideSlashCommandMenu,
    setThreadStatusCard: deps.setThreadStatusCard,
    blockInSandbox: deps.blockInSandbox,
    localStorageRef,
    FAST_MODE_DEVICE_DEFAULT_KEY: deps.FAST_MODE_DEVICE_DEFAULT_KEY,
    PERMISSION_PRESET_STORAGE_KEY: deps.PERMISSION_PRESET_STORAGE_KEY,
  });

  const actionBindings = deps.createActionBindingsModule({
    state: deps.state,
    byId: deps.byId,
    api,
    bindClick: deps.bindClick,
    bindResponsiveClick: deps.bindResponsiveClick,
    bindInput: deps.bindInput,
    setStatus: deps.setStatus,
    addChat: chatTimeline.addChat,
    updateMobileComposerState: deps.updateMobileComposerState,
    refreshActiveThreadGitMeta: deps.refreshActiveThreadGitMeta,
    updateNotificationState: deps.updateNotificationState,
    armSyntheticClickSuppression: deps.armSyntheticClickSuppression,
    wireBlurBackdropShield: deps.wireBlurBackdropShield,
    clearThreadStatusCard: deps.clearThreadStatusCard,
    closeFolderPicker: folderPicker.closeFolderPicker,
    refreshFolderPicker: folderPicker.refreshFolderPicker,
    renderFolderPicker: folderPicker.renderFolderPicker,
    confirmFolderPickerCurrentPath: folderPicker.confirmFolderPickerCurrentPath,
    resetFolderPickerPath: folderPicker.resetFolderPickerPath,
    switchFolderPickerWorkspace: folderPicker.switchFolderPickerWorkspace,
    openFolderPicker: folderPicker.openFolderPicker,
    newThread: turnActions.newThread,
    setMainTab: deps.setMainTab,
    setMobileTab: deps.setMobileTab,
    refreshCodexVersions: deps.refreshCodexVersions,
    setWorkspaceTarget: workspaceUi.setWorkspaceTarget,
    setHeaderModelMenuOpen: modelPicker.setHeaderModelMenuOpen,
    closeInlineEffortOverlay: modelPicker.closeInlineEffortOverlay,
    shouldSuppressSyntheticClick: deps.shouldSuppressSyntheticClick,
    renderThreads: (...args) => renderThreads(...args),
    wireThreadPullToRefresh,
    addHost: turnActions.addHost,
    resolveApproval: turnActions.resolveApproval,
    resolveProposedPlanConfirmation: turnActions.resolveProposedPlanConfirmation,
    resolveUserInput: turnActions.resolveUserInput,
    refreshPending: connectionFlows.refreshPending,
    getPendingUserInputDraftAnswers: connectionFlows.getPendingUserInputDraftAnswers,
    getPendingUserInputSubmissionState: connectionFlows.getPendingUserInputSubmissionState,
    setPendingUserInputDraftAnswer: connectionFlows.setPendingUserInputDraftAnswer,
    setPendingUserInputQuestionCompleted: connectionFlows.setPendingUserInputQuestionCompleted,
    uploadAttachment: turnActions.uploadAttachment,
      executeSlashCommand: turnActions.executeSlashCommand,
      cancelQueuedTurnEditing: turnActions.cancelQueuedTurnEditing,
      clearQueuedTurn: turnActions.clearQueuedTurn,
      editQueuedTurn: turnActions.editQueuedTurn,
      maybeRestoreDeferredQueuedTurnEdit: turnActions.maybeRestoreDeferredQueuedTurnEdit,
      openManagedTerminalSurface: turnActions.openManagedTerminalSurface,
      queueFollowUpTurn: turnActions.queueFollowUpTurn,
      saveQueuedTurnEdit: turnActions.saveQueuedTurnEdit,
      sendNowTurn: turnActions.sendNowTurn,
      sendQueuedTurnNow: turnActions.sendQueuedTurnNow,
      sendTurn: turnActions.sendTurn,
      scrollToBottomReliable: chatViewport.scrollToBottomReliable,
      steerTurn: turnActions.steerTurn,
      setComposerActionMenuOpen: deps.setComposerActionMenuOpen,
      syncSlashCommandMenu: deps.syncSlashCommandMenu,
      handleSlashCommandKeyDown: deps.handleSlashCommandKeyDown,
      syncSettingsControlsFromMain: deps.syncSettingsControlsFromMain,
      updateQueuedTurnEditingDraft: turnActions.updateQueuedTurnEditingDraft,
      LIVE_INSPECTOR_ENABLED_KEY: deps.LIVE_INSPECTOR_ENABLED_KEY,
    localStorageRef,
    windowRef,
    documentRef,
  });

  const debugTools = deps.createDebugToolsModule({
    state: deps.state,
    byId: deps.byId,
    addChat: chatTimeline.addChat,
    renderInlineMessageText: deps.renderInlineMessageText,
    findNextInlineCodeSpan: deps.findNextInlineCodeSpan,
    normalizeWorkspaceTarget: deps.normalizeWorkspaceTarget,
    detectThreadWorkspaceTarget: deps.detectThreadWorkspaceTarget,
    normalizeModelOption: deps.normalizeModelOption,
    ensureArrayItems: deps.ensureArrayItems,
    pickLatestModelId: deps.pickLatestModelId,
    REASONING_EFFORT_KEY: deps.REASONING_EFFORT_KEY,
    MODEL_LOADING_MIN_MS: deps.MODEL_LOADING_MIN_MS,
    normalizeThreadTokenUsage: deps.normalizeThreadTokenUsage,
    renderRuntimePanels: deps.renderRuntimePanels,
    renderCommentaryArchive: chatTimeline.renderCommentaryArchive,
    renderPendingInline: chatTimeline.renderPendingInline,
    renderPendingLists: connectionFlows.renderPendingLists,
    getVisiblePendingUserInputs: connectionFlows.getVisiblePendingUserInputs,
    renderComposerContextLeft: deps.renderComposerContextLeft,
    clearChatMessages: chatTimeline.clearChatMessages,
    showWelcomeCard: deps.showWelcomeCard,
    updateHeaderUi: deps.updateHeaderUi,
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    getStartCwdForWorkspace: workspaceUi.getStartCwdForWorkspace,
    parseUserMessageParts: deps.parseUserMessageParts,
    renderMessageAttachments: deps.renderMessageAttachments,
    setMainTab: deps.setMainTab,
    setMobileTab: deps.setMobileTab,
    setActiveThread: deps.setActiveThread,
    setActivePlan: deps.setActivePlan,
    setActiveCommands: deps.setActiveCommands,
    setRuntimeActivity: deps.setRuntimeActivity,
    setChatOpening: chatTimeline.setChatOpening,
    loadThreadMessages: historyLoader.loadThreadMessages,
    refreshThreads: (...args) => refreshThreads(...args),
    handleWsPayload,
    scrollChatToBottom: chatViewport.scrollChatToBottom,
    scrollToBottomReliable: chatViewport.scrollToBottomReliable,
    createAssistantStreamingMessage: chatTimeline.createAssistantStreamingMessage,
    appendStreamingDelta: chatTimeline.appendStreamingDelta,
    setStatus: deps.setStatus,
    isThreadAnimDebugEnabled: deps.isThreadAnimDebugEnabled,
    pushThreadAnimDebug: deps.pushThreadAnimDebug,
    threadAnimDebug: deps.threadAnimDebug,
    WEB_CODEX_DEV_DEBUG_VERSION: deps.WEB_CODEX_DEV_DEBUG_VERSION,
    LIVE_INSPECTOR_ENABLED_KEY: deps.LIVE_INSPECTOR_ENABLED_KEY,
    localStorageRef,
    setHeaderModelMenuOpen: modelPicker.setHeaderModelMenuOpen,
    renderHeaderModelMenu: modelPicker.renderHeaderModelMenu,
    setWorkspaceTarget: workspaceUi.setWorkspaceTarget,
    setStartCwdForWorkspace: workspaceUi.setStartCwdForWorkspace,
  });

  ({
    wireThreadPullToRefresh,
    startThreadAutoRefreshLoop,
    startActiveThreadLivePollLoop,
  } = deps.createThreadLiveModule({
    state: deps.state,
    byId: deps.byId,
    waitMs: deps.waitMs,
    setStatus: deps.setStatus,
    refreshThreads: (...args) => refreshThreads(...args),
    refreshCodexVersions: deps.refreshCodexVersions,
    getWorkspaceTarget: workspaceUi.getWorkspaceTarget,
    loadThreadMessages: historyLoader.loadThreadMessages,
    THREAD_PULL_REFRESH_TRIGGER_PX: deps.THREAD_PULL_REFRESH_TRIGGER_PX,
    THREAD_PULL_REFRESH_MAX_PX: deps.THREAD_PULL_REFRESH_MAX_PX,
    THREAD_PULL_REFRESH_MIN_MS: deps.THREAD_PULL_REFRESH_MIN_MS,
    THREAD_PULL_HINT_CLEAR_DELAY_MS: deps.THREAD_PULL_HINT_CLEAR_DELAY_MS,
    THREAD_AUTO_REFRESH_CONNECTED_MS: deps.THREAD_AUTO_REFRESH_CONNECTED_MS,
    THREAD_AUTO_REFRESH_DISCONNECTED_MS: deps.THREAD_AUTO_REFRESH_DISCONNECTED_MS,
    ACTIVE_THREAD_LIVE_POLL_MS: deps.ACTIVE_THREAD_LIVE_POLL_MS,
    ACTIVE_THREAD_LIVE_POLL_WS_FALLBACK_MS: deps.ACTIVE_THREAD_LIVE_POLL_WS_FALLBACK_MS,
  }));

  const bootstrapApp = deps.createBootstrapModule({
    state: deps.state,
    byId: deps.byId,
    installDebugAndE2E: debugTools.installDebugAndE2E,
    installMobileViewportSync: deps.installMobileViewportSync,
    getEmbeddedToken: deps.getEmbeddedToken,
    localStorageRef,
    documentRef,
    requestAnimationFrameRef,
    MutationObserverRef,
    normalizeWorkspaceTarget: deps.normalizeWorkspaceTarget,
    normalizeStartCwd: deps.normalizeStartCwd,
    restoreModelsCache: deps.restoreModelsCache,
    restoreThreadsCache: deps.restoreThreadsCache,
    updateWorkspaceAvailability: threadListRefresh.updateWorkspaceAvailability,
    applyWorkspaceUi: workspaceUi.applyWorkspaceUi,
    syncHeaderModelPicker: modelPicker.syncHeaderModelPicker,
    setStatus: deps.setStatus,
    updateNotificationState: deps.updateNotificationState,
    applyManagedTokenUi: deps.applyManagedTokenUi,
    renderPendingLists: connectionFlows.renderPendingLists,
    renderFolderPicker: folderPicker.renderFolderPicker,
    renderAttachmentPills: deps.renderAttachmentPills,
    renderComposerContextLeft: deps.renderComposerContextLeft,
    renderRuntimePanels: deps.renderRuntimePanels,
    updateMobileComposerState: deps.updateMobileComposerState,
    refreshSlashCommandsState: deps.refreshSlashCommandsState,
    syncSettingsControlsFromMain: deps.syncSettingsControlsFromMain,
    updateWelcomeSelections: deps.updateWelcomeSelections,
    setMainTab: deps.setMainTab,
    wireActions: actionBindings.wireActions,
    ensureScrollToBottomBtn: chatViewport.ensureScrollToBottomBtn,
    stopChatLiveFollow: chatViewport.stopChatLiveFollow,
    updateScrollToBottomBtn: chatViewport.updateScrollToBottomBtn,
    chatDistanceFromBottom: chatViewport.chatDistanceFromBottom,
    dbgSet: deps.dbgSet,
    canStartChatLiveFollow: chatViewport.canStartChatLiveFollow,
    scheduleChatLiveFollow: chatViewport.scheduleChatLiveFollow,
    startThreadAutoRefreshLoop,
    startActiveThreadLivePollLoop,
    setMobileTab: deps.setMobileTab,
    connect: connectionFlows.connect,
    transportMode: deps.transportMode,
    GUIDE_DISMISSED_KEY: deps.GUIDE_DISMISSED_KEY,
    TOKEN_STORAGE_KEY: deps.TOKEN_STORAGE_KEY,
    WORKSPACE_TARGET_KEY: deps.WORKSPACE_TARGET_KEY,
    START_CWD_BY_WORKSPACE_KEY: deps.START_CWD_BY_WORKSPACE_KEY,
    FAVORITE_THREADS_KEY: deps.FAVORITE_THREADS_KEY,
    SELECTED_MODEL_KEY: deps.SELECTED_MODEL_KEY,
    ACTIVE_MAIN_TAB_KEY: deps.ACTIVE_MAIN_TAB_KEY,
    FAST_MODE_DEVICE_DEFAULT_KEY: deps.FAST_MODE_DEVICE_DEFAULT_KEY,
    PERMISSION_PRESET_STORAGE_KEY: deps.PERMISSION_PRESET_STORAGE_KEY,
    SANDBOX_MODE: deps.SANDBOX_MODE,
    CHAT_STICKY_BOTTOM_PX: deps.CHAT_STICKY_BOTTOM_PX,
  });

  const {
    applyWorkspaceUi,
    getActiveWorkspaceBadgeLabel,
    getStartCwdForWorkspace,
    getWorkspaceLabel,
    getWorkspaceTarget,
    hasDualWorkspaceTargets,
    isWorkspaceAvailable,
    getWorkspaceRuntimeState,
    persistStartCwdByWorkspace,
    refreshWorkspaceRuntimeState,
    setStartCwdForWorkspace,
    setWorkspaceTarget,
    syncActiveThreadMetaFromList,
  } = workspaceUi;
  const {
    canStartChatLiveFollow,
    chatDistanceFromBottom,
    ensureScrollToBottomBtn,
    isChatNearBottom,
    isChatNearBottomForJumpBtn,
    scheduleChatLiveFollow,
    scrollChatToBottom,
    scrollToBottomReliable,
    smoothScrollChatToBottom,
    stopChatLiveFollow,
    updateScrollToBottomBtn,
  } = chatViewport;
  const {
    ensureImageViewer,
    openImageViewer,
    wireMessageAttachments,
  } = imageViewer;
  const {
    addChat,
    appendStreamingDelta,
    buildMsgNode,
    clearChatMessages,
    createAssistantStreamingMessage,
    finalizeAssistantMessage,
    renderCommentaryArchive,
    renderAssistantLiveBody,
    renderPendingInline,
    setChatOpening,
  } = chatTimeline;
  const { applyThreadToChat, loadThreadMessages, updateLoadOlderControl } = historyLoader;
  const {
    closeInlineEffortOverlay,
    ensureInlineEffortOverlay,
    openInlineEffortOverlay,
    refreshModels,
    renderHeaderModelMenu,
    setHeaderModelMenuOpen,
    syncHeaderModelPicker,
  } = modelPicker;
  const {
    applyThreadFilter,
    isThreadListActuallyVisible,
    refreshThreads,
    scheduleThreadListDeferredRender,
    scheduleThreadListVisibleAnimationRender,
    updateWorkspaceAvailability,
    updateWorkspaceAvailabilityFromThreads,
  } = threadListRefresh;
  const {
    closeFolderPicker,
    confirmFolderPickerCurrentPath,
    openFolderPicker,
    refreshFolderPicker,
    renderFolderPicker,
    resetFolderPickerPath,
    switchFolderPickerWorkspace,
  } = folderPicker;
  const {
    applyPendingPayloads,
    clearPendingUserInputs,
    clearSyntheticPendingUserInputById,
    connect,
    getVisiblePendingUserInputs,
    getPendingUserInputSubmissionState,
    refreshAll,
    refreshHosts,
    refreshPending,
    refreshPendingFromHttp,
    renderHosts,
    renderPendingLists,
    setActiveHost,
    suppressSyntheticPendingUserInputs,
    setSyntheticPendingUserInputs,
    upsertSyntheticPendingUserInput,
  } = connectionFlows;
  const { addHost, clearQueuedTurn, editQueuedTurn, executeSlashCommand, flushQueuedTurn, interruptTurn, newThread, queueFollowUpTurn, resolveApproval, resolveUserInput, sendNowTurn, sendQueuedTurnNow, sendTurn, steerTurn, uploadAttachment } =
    turnActions;
  const { wireActions } = actionBindings;
  const { installDebugAndE2E } = debugTools;
  const { bootstrap } = bootstrapApp;

  return {
    api,
    connectWs,
    handleWsPayload,
    wsCall,
    wsSend,
    applyWorkspaceUi,
    getActiveWorkspaceBadgeLabel,
    getStartCwdForWorkspace,
    getWorkspaceLabel,
    getWorkspaceTarget,
    hasDualWorkspaceTargets,
    isWorkspaceAvailable,
    getWorkspaceRuntimeState,
    persistStartCwdByWorkspace,
    refreshWorkspaceRuntimeState,
    setStartCwdForWorkspace,
    setWorkspaceTarget,
    syncActiveThreadMetaFromList,
    canStartChatLiveFollow,
    chatDistanceFromBottom,
    ensureScrollToBottomBtn,
    isChatNearBottom,
    isChatNearBottomForJumpBtn,
    scheduleChatLiveFollow,
    scrollChatToBottom,
    scrollToBottomReliable,
    smoothScrollChatToBottom,
    stopChatLiveFollow,
    updateScrollToBottomBtn,
    ensureImageViewer,
    openImageViewer,
    wireMessageAttachments,
    addChat,
    appendStreamingDelta,
    buildMsgNode,
    clearChatMessages,
    createAssistantStreamingMessage,
    finalizeAssistantMessage,
    renderCommentaryArchive,
    renderAssistantLiveBody,
    renderPendingInline,
    setChatOpening,
    applyThreadToChat,
    loadThreadMessages,
    updateLoadOlderControl,
    closeInlineEffortOverlay,
    ensureInlineEffortOverlay,
    openInlineEffortOverlay,
    refreshModels,
    renderHeaderModelMenu,
    setHeaderModelMenuOpen,
    syncHeaderModelPicker,
    applyThreadFilter,
    isThreadListActuallyVisible,
    refreshThreads,
    scheduleThreadListDeferredRender,
    scheduleThreadListVisibleAnimationRender,
    updateWorkspaceAvailability,
    updateWorkspaceAvailabilityFromThreads,
    renderThreads,
    closeFolderPicker,
    confirmFolderPickerCurrentPath,
    openFolderPicker,
    refreshFolderPicker,
    renderFolderPicker,
    resetFolderPickerPath,
    switchFolderPickerWorkspace,
    applyPendingPayloads,
    connect,
    getVisiblePendingUserInputs,
    refreshAll,
    refreshHosts,
    refreshPending,
    refreshPendingFromHttp,
    renderHosts,
    renderPendingLists,
    clearPendingUserInputs,
    clearSyntheticPendingUserInputById,
    setActiveHost,
    suppressSyntheticPendingUserInputs,
    setSyntheticPendingUserInputs,
    upsertSyntheticPendingUserInput,
    addHost,
    clearQueuedTurn,
    editQueuedTurn,
    executeSlashCommand,
    flushQueuedTurn,
    interruptTurn,
    newThread,
    queueFollowUpTurn,
    resolveApproval,
    resolveUserInput,
    sendNowTurn,
    sendQueuedTurnNow,
    sendTurn,
    steerTurn,
    uploadAttachment,
    wireActions,
    installDebugAndE2E,
    wireThreadPullToRefresh,
    startThreadAutoRefreshLoop,
    startActiveThreadLivePollLoop,
    bootstrap,
  };
}
