import { describe, expect, it, vi } from "vitest";

import { createCodexWebComposition } from "./composition.js";

function stubFactory(result) {
  return vi.fn(() => result);
}

describe("composition", () => {
  it("wires module outputs into one composition object", () => {
    const createActionBindingsModule = vi.fn(() => ({ wireActions: () => {} }));
    const composition = createCodexWebComposition({
      state: {},
      byId: () => null,
      setStatus: () => {},
      toRecord: (v) => v,
      readString: (v) => v,
      readNumber: (v) => v,
      resetEventReplayState: () => {},
      markEventIdSeen: () => {},
      extractNotificationEventId: () => null,
      extractNotificationThreadId: () => null,
      shouldRefreshThreadsFromNotification: () => false,
      shouldRefreshActiveThreadFromNotification: () => false,
      scheduleThreadRefresh: () => {},
      scheduleActiveThreadRefresh: () => {},
      renderLiveNotification: () => {},
      normalizeWorkspaceTargetInModule: (v) => v,
      updateHeaderUi: () => {},
      dbgSet: () => {},
      waitMs: async () => {},
      normalizeThreadTokenUsage: (v) => v,
      renderComposerContextLeft: () => {},
      parseUserMessageParts: () => ({}),
      isBootstrapAgentsPrompt: () => false,
      normalizeThreadItemText: (v) => v,
      normalizeType: (v) => v,
      stripCodexImageBlocks: (v) => v,
      hideWelcomeCard: () => {},
      showWelcomeCard: () => {},
      renderMessageBody: () => "",
      ensureArrayItems: (v) => v || [],
      escapeHtml: (v) => String(v || ""),
      escapeAttr: (v) => String(v || ""),
      compactModelLabel: (v) => v,
      persistModelsCache: () => {},
      pickLatestModelId: () => "m",
      normalizeWorkspaceTarget: (v) => v,
      sortThreadsByNewest: (v) => v,
      filterThreadsForWorkspace: (v) => v,
      detectWorkspaceAvailabilityFromThreads: () => ({}),
      buildThreadRenderSig: () => "sig",
      persistThreadsCache: () => {},
      pushThreadAnimDebug: () => {},
      truncateLabel: (v) => v,
      relativeTimeLabel: (v) => String(v),
      pickThreadTimestamp: () => 0,
      setMainTab: () => {},
      setMobileTab: () => {},
      setActiveThread: () => {},
      renderAttachmentPills: () => {},
      blockInSandbox: () => false,
      getEmbeddedToken: () => "",
      refreshCodexVersions: async () => {},
      getPromptValue: () => "",
      waitPendingThreadResume: async () => {},
      registerPendingThreadResume: () => {},
      clearPromptValue: () => {},
      normalizeTextPayload: (v) => v,
      maybeNotifyTurnDone: () => {},
      updateNotificationState: () => {},
      refreshActiveThreadGitMeta: async () => {},
      armSyntheticClickSuppression: () => {},
      wireBlurBackdropShield: () => {},
      bindClick: () => {},
      bindResponsiveClick: () => {},
      bindInput: () => {},
      renderInlineMessageText: () => "",
      findNextInlineCodeSpan: () => null,
      normalizeModelOption: (v) => v,
      threadAnimDebug: {},
      WEB_CODEX_DEV_DEBUG_VERSION: "x",
      normalizeStartCwd: (v) => v,
      restoreModelsCache: () => false,
      restoreThreadsCache: () => false,
      syncSettingsControlsFromMain: () => {},
      updateWelcomeSelections: () => {},
      GUIDE_DISMISSED_KEY: "g",
      TOKEN_STORAGE_KEY: "t",
      WORKSPACE_TARGET_KEY: "w",
      START_CWD_BY_WORKSPACE_KEY: "s",
      FAVORITE_THREADS_KEY: "f",
      SELECTED_MODEL_KEY: "m",
      SANDBOX_MODE: false,
      CHAT_STICKY_BOTTOM_PX: 12,
      HISTORY_WINDOW_THRESHOLD: 180,
      CHAT_LIVE_FOLLOW_MAX_STEP_PX: 64,
      CHAT_LIVE_FOLLOW_BTN_THROTTLE_MS: 66,
      SELECTED_MODEL_KEY: "sel",
      REASONING_EFFORT_KEY: "r",
      MODEL_USER_SELECTED_KEY: "mu",
      EFFORT_USER_SELECTED_KEY: "eu",
      MODEL_LOADING_MIN_MS: 1000,
      THREAD_FORCE_REFRESH_MIN_INTERVAL_MS: 1,
      THREAD_PULL_REFRESH_TRIGGER_PX: 1,
      THREAD_PULL_REFRESH_MAX_PX: 1,
      THREAD_PULL_REFRESH_MIN_MS: 1,
      THREAD_PULL_HINT_CLEAR_DELAY_MS: 1,
      THREAD_AUTO_REFRESH_CONNECTED_MS: 1,
      THREAD_AUTO_REFRESH_DISCONNECTED_MS: 1,
      ACTIVE_THREAD_LIVE_POLL_MS: 1,
      LAST_EVENT_ID_KEY: "last",
      createWsClientModule: stubFactory({ api: async () => ({}), connectWs: () => {}, handleWsPayload: () => {}, wsCall: () => {}, wsSend: () => {} }),
      createWorkspaceUiModule: stubFactory({ applyWorkspaceUi: () => {}, getActiveWorkspaceBadgeLabel: () => "WIN", getStartCwdForWorkspace: () => "", getWorkspaceLabel: () => "", getWorkspaceTarget: () => "windows", hasDualWorkspaceTargets: () => false, isWorkspaceAvailable: () => true, persistStartCwdByWorkspace: () => {}, setStartCwdForWorkspace: () => {}, setWorkspaceTarget: () => {}, syncActiveThreadMetaFromList: () => {} }),
      createChatViewportModule: stubFactory({ canStartChatLiveFollow: () => false, chatDistanceFromBottom: () => 0, ensureScrollToBottomBtn: () => {}, isChatNearBottom: () => true, isChatNearBottomForJumpBtn: () => true, scheduleChatLiveFollow: () => {}, scrollChatToBottom: () => {}, scrollToBottomReliable: () => {}, smoothScrollChatToBottom: () => {}, stopChatLiveFollow: () => {}, updateScrollToBottomBtn: () => {} }),
      createImageViewerModule: stubFactory({ ensureImageViewer: () => {}, openImageViewer: () => {}, wireMessageAttachments: () => {} }),
      createChatTimelineModule: stubFactory({ addChat: () => {}, appendStreamingDelta: () => {}, buildMsgNode: () => {}, clearChatMessages: () => {}, createAssistantStreamingMessage: () => {}, finalizeAssistantMessage: () => {}, setChatOpening: () => {} }),
      createHistoryLoaderModule: stubFactory({ applyThreadToChat: () => {}, loadThreadMessages: () => {}, updateLoadOlderControl: () => {} }),
      createModelPickerModule: stubFactory({ closeInlineEffortOverlay: () => {}, ensureInlineEffortOverlay: () => {}, openInlineEffortOverlay: () => {}, refreshModels: () => {}, renderHeaderModelMenu: () => {}, setHeaderModelMenuOpen: () => {}, syncHeaderModelPicker: () => {} }),
      createThreadListRefreshModule: stubFactory({ applyThreadFilter: () => {}, isThreadListActuallyVisible: () => false, refreshThreads: () => {}, scheduleThreadListDeferredRender: () => {}, scheduleThreadListVisibleAnimationRender: () => {}, updateWorkspaceAvailability: () => {}, updateWorkspaceAvailabilityFromThreads: () => {} }),
      createThreadListViewModule: stubFactory({ renderThreads: () => {} }),
      createFolderPickerModule: stubFactory({ closeFolderPicker: () => {}, confirmFolderPickerCurrentPath: () => {}, openFolderPicker: () => {}, refreshFolderPicker: () => {}, renderFolderPicker: () => {}, resetFolderPickerPath: () => {}, switchFolderPickerWorkspace: () => {} }),
      createConnectionFlowsModule: stubFactory({ applyPendingPayloads: () => {}, connect: () => {}, refreshAll: () => {}, refreshHosts: () => {}, refreshPending: () => {}, refreshPendingFromHttp: () => {}, renderHosts: () => {}, renderPendingLists: () => {}, setActiveHost: () => {} }),
      createTurnActionsModule: stubFactory({ addHost: () => {}, newThread: () => {}, resolveApproval: () => {}, resolveUserInput: () => {}, sendTurn: () => {}, uploadAttachment: () => {} }),
      createActionBindingsModule,
      createDebugToolsModule: stubFactory({ installDebugAndE2E: () => {} }),
      createThreadLiveModule: stubFactory({ wireThreadPullToRefresh: () => {}, startThreadAutoRefreshLoop: () => {}, startActiveThreadLivePollLoop: () => {} }),
      createBootstrapModule: stubFactory({ bootstrap: () => {} }),
    });

    expect(typeof composition.bootstrap).toBe("function");
    expect(typeof composition.refreshThreads).toBe("function");
    expect(typeof composition.setHeaderModelMenuOpen).toBe("function");
    expect(createActionBindingsModule).toHaveBeenCalledWith(
      expect.objectContaining({
        refreshActiveThreadGitMeta: expect.any(Function),
      })
    );
  });
});
