import { useProviderCrudActions } from './providerActions/useProviderCrudActions'
import { useProviderKeyActions } from './providerActions/useProviderKeyActions'
import { useProviderUsageActions } from './providerActions/useProviderUsageActions'
import type { UseProviderActionsParams, UseProviderActionsResult } from './providerActions/types'

export function useProviderActions({
  config,
  status,
  setStatus,
  isDevPreview,
  setConfig,
  keyModal,
  providerBaseUrlModal,
  providerEmailModal,
  usageBaseModal,
  usageAuthModal,
  newProviderName,
  newProviderBaseUrl,
  newProviderKey,
  newProviderKeyStorage,
  setKeyModal,
  setProviderBaseUrlModal,
  setProviderEmailModal,
  setUsageBaseModal,
  setUsageAuthModal,
  setNewProviderName,
  setNewProviderBaseUrl,
  setNewProviderKey,
  setNewProviderKeyStorage,
  setRefreshingProviders,
  refreshStatus,
  refreshConfig,
  flashToast,
}: UseProviderActionsParams): UseProviderActionsResult {
  const {
    refreshQuota,
    refreshQuotaAll,
    saveUsageBaseUrl,
    saveUsageAuth,
    clearUsageAuth,
    saveProviderEmail,
    clearProviderEmail,
    setUsageBaseUrl,
    clearUsageBaseUrl,
    setProviderQuotaHardCap,
    openUsageBaseModal,
    openUsageAuthModal,
    openProviderEmailModal,
  } = useProviderUsageActions({
    config,
    status,
    setStatus,
    setConfig,
    isDevPreview,
    providerEmailModal,
    usageBaseModal,
    usageAuthModal,
    setProviderEmailModal,
    setUsageBaseModal,
    setUsageAuthModal,
    setRefreshingProviders,
    refreshStatus,
    refreshConfig,
    flashToast,
  })

  const {
    saveProvider,
    saveProviderBaseUrl,
    setProviderSupportsWebsockets,
    setProviderGroup,
    setProvidersGroup,
    setProviderDisabled,
    deleteProvider,
    openProviderBaseUrlModal,
    addProvider,
  } = useProviderCrudActions({
    config,
    isDevPreview,
    setConfig,
    providerBaseUrlModal,
    refreshQuota,
    newProviderName,
    newProviderBaseUrl,
    newProviderKey,
    newProviderKeyStorage,
    setProviderBaseUrlModal,
    setNewProviderName,
    setNewProviderBaseUrl,
    setNewProviderKey,
    setNewProviderKeyStorage,
    refreshStatus,
    refreshConfig,
    flashToast,
  })

  const { saveKey, clearKey, openKeyModal } = useProviderKeyActions({
    keyModal,
    config,
    isDevPreview,
    setKeyModal,
    refreshStatus,
    refreshConfig,
    flashToast,
  })

  return {
    saveProvider,
    setProviderGroup,
    setProvidersGroup,
    setProviderDisabled,
    deleteProvider,
    saveKey,
    clearKey,
    refreshQuota,
    refreshQuotaAll,
    saveUsageBaseUrl,
    saveUsageAuth,
    clearUsageAuth,
    saveProviderEmail,
    clearProviderEmail,
    saveProviderBaseUrl,
    setProviderSupportsWebsockets,
    setUsageBaseUrl,
    clearUsageBaseUrl,
    setProviderQuotaHardCap,
    openKeyModal,
    openProviderBaseUrlModal,
    openUsageBaseModal,
    openUsageAuthModal,
    openProviderEmailModal,
    addProvider,
  }
}
